### PR TITLE
Add hamming

### PR DESCRIPTION
**Pull request by cmiller01**
i included difference-of-squares in this PR as well, just turned out to be easier and figured the config.json file might conflict if these were separate. happy to break up if that's better.

### CODE REVIEW

**Comment by cmiller01** [comment]
@jonboiser @kytrinyx wondering if you could take a look at this? Would like to get more exercises into the R track.

**Comment by kytrinyx** [comment]
Thanks @cmiller01—I'm looking at these today. I've merged difference of squares and will pull this down locally so we just get hamming in this PR.

I think that `config.json` won't conflict if you put some things earlier in the list (as opposed to at the end). This does affect the order that the exercises are delivered, so sometimes it won't make sense to put things earlier, but if it does make sense that would be a way to avoid the conflicts.

**Comment by kytrinyx** [comment]
Merged in d4c904de1abec5811227fca0cd97d3438c378d6b

**Comment by cmiller01** [comment]
Thanks @kytrinyx, good call on the ordering exercises in config.json. I'll work on getting more of these created. Would love for R not to be an orphaned repo for exercism.

**Comment by kytrinyx** [comment]
> Would love for R not to be an orphaned repo for exercism.

I would love that too! :heart:

**Pull request closed without merging**
